### ISSUE TITLE
Update .gitignore to handle Eclipse and Netbeans files

### ISSUE THREAD

**Issue by pwright4** [MSUCSIS/Inference#23]
The current .gitignore ignore the target directory generated by Maven and the project settings in IntelliJ, but not the project files for Netbeans and Eclipse. I suspect others will be using these IDEs, so it would be good to update the file accordingly.

**Comment by jdennerlein** [comment]
I can do this.

**Comment by pwright4** [comment]
You got it.

**Comment by pwright4** [comment]
Closing after merging code from pull request #26
